model:
  dataset_conf: config/datasets/titan_refacto.json
  model_conf: null
  model_name: HalfUNet
  lr: 0.1
  loss_name: mse
  num_inter_steps: 1
  num_samples_to_plot: 1
  training_strategy: diff_ar
  save_path: /scratch/shared/py4cast/logs/camp0/test_cli_lea/
  use_lr_scheduler: false
  no_log: false
  channels_last: false
data:
  dataset_name: titan_refacto
  num_input_steps: 1
  num_pred_steps_train: 1
  num_pred_steps_val_test: 1
  batch_size: 1
  num_workers: 10
# optimizer: null
# lr_scheduler: null